version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: ms-db
    environment:
      POSTGRES_DB: ms-project
      POSTGRES_USER: elias
      POSTGRES_PASSWORD: elias
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: